server:
  port: 8802

spring:
  application:
    name: business
  cloud:
    nacos:
      discovery:
        server-addr: http://localhsot:8848
        group: SEATA_GROUP
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/business?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
#    type: com.alibaba.druid.pool.DruidDataSource

seata:
  tx-service-group: mygroup
  service:
    vgroup-mapping:
      mygroup: default
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      group: "DEFAULT_GROUP"
      namespace: "public"
      username: "nacos"
      password: "nacos"







